- 넘파이와 리스트의 차이점.
1. 모든 원소가 같은 자료형이어야 한다. = 배열
2. 초기 생성한 원소의 갯수를 바꿀 수 없다.

- 넘파이의 장점
  - 굉장히 큰 matrix처리 및 다양한 연산 기능 제공
  - 반복문 없이 데이터 배열에 대한 처리 지원
  - 선형대수와 관련된 다양한 기능 제공

- 속도가 빠른 이유.
  - numpy는 c언어로 구현되어 있음
  - numpy는 task를 subtask로 알아서 나눠 병렬적으로 처리한다
  - 메모리 접근 방식에 대한 차이로 인하여 속도가 빠르다 (주소값 저장이 아닌 실제 값을 메모리에 가지고 있어 메모리에 값이 연속적으로 저장이 되어 있고 이로 인하여 속도가 빠른다.)

- 행렬의 필요성 [행렬은 어디에 쓰일까.]
  - 컴퓨터의 메모리 구조는 행렬 형태로 표현이 가능합니다.
  - 표 형태의 데이터는 행렬로 표현될 수 있습니다.





In [122]:
import numpy as np

# 넘파이 생성 방법
arr  = np.array([1,2,3])
print(arr,'\n')
type(arr)


# 모든 자료형이 통일 된걸 확인
arr  = np.array([1.1,2,3])
print(arr)
type(arr)
print(arr.dtype,'\n')

# 2차원 배열 생성
arr  = np.array([[1,2,3],[4,5,6]])
print(arr,'\n')

# 3차원 배열 생성
arr  = np.array([[[1],[2]],[[3],[4]]])
print(arr)


[1 2 3] 

[1.1 2.  3. ]
float64 

[[1 2 3]
 [4 5 6]] 

[[[1]
  [2]]

 [[3]
  [4]]]


In [134]:
# 두번째 방법 기본값이 있는 배열 만들기
arr = np.zeros(10, dtype=np.int32) # 32bit의 범위 = -21억~21억
print(arr)

arr = np.zeros((3,3)) # 기본데이터 타입을 실수형으로 저장
print(arr)

[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [135]:
arr = np.ones(10, dtype=np.int32) # 32bit의 범위 = -21억~21억
print(arr)

arr = np.ones((3,3))
arr

[1 1 1 1 1 1 1 1 1 1]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [141]:
# 세번째 방법 연속된 값이 있는 배열 만들기
arr = np.arange(1,10,2) # 시작, 끝, 간격
print(arr)

# 0~100을 6조각으로 나눈다.
arr = np.linspace(0,100,6, dtype=np.int32)
print(arr)

[1 3 5 7 9]
[  0  20  40  60  80 100]


In [143]:
# 배열의 차원과 크기 알아내기
arr = np.linspace(0,100,3, dtype=np.int32)

print(arr.ndim) # 행 갯수 = 몇 차원인지
print(arr.shape) # 행 갯수
a1 = np.array( [ 1, 2, 3, 4, 5 ])
a2 = np.array( [ [ 1, 2, 3, 4 ] , [ 1, 2, 3, 4 ] ] )
a3 = np.array( [ [ [ 1, 2, 3 ] , [ 1, 2, 3 ] ] ,
                     [ [ 1, 2, 3 ] , [ 1, 2, 3 ] ] ,
                     [ [ 1, 2, 3 ] , [ 1, 2, 3 ] ] ] )

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

print(a1.shape) #(5,) = 1행, 5열
print(a2.shape) #(2, 4) = 2행, 4열
print(a3.shape) #(3, 2, 3) = 3높이의, 2행의, 3개의 열

# 스칼라  단행, 1행의 데이터
# 벡터  2차원 배열
# 텐서 3차원 이상

1
(3,)
1
2
4
(5,)
(2, 4)
(3, 3, 3, 3)


In [78]:
# 읽는 방법. 
# 인덱싱과 슬라이싱

arr = np.array( [ [ 0, 1, 2 ], 
                  [ 3, 4, 5 ],
                  [ 6, 7, 8 ] ])
print(arr.shape)

#인덱싱
print(arr[2,2])
print(arr[0,0])

#음수 인덱싱
print(arr[-1,-1]) # 8
print(arr[-2,-2]) # 4

(3, 3)
8
[0 3 6]
8
4


In [101]:
# 슬라이싱
arr = np.array( [ [ 1, 2, 3, 4, 5 ],
                  [ 6, 7, 8, 9, 10 ],
                  [ 11, 12, 13, 14, 15] ] )

print(arr.shape)
print(arr[0:1,::-2])
print(arr[1:2,:])

(3, 5)
[[5 3 1]]
[[ 6  7  8  9 10]]


In [102]:
#불리언 배열 인덱싱

arr = np.array([0,1,2,3,4,5])
bool_arr = np.array([True,False,True,False,True,False])

# 불리언 인덱싱을 사용할때 주의할점은 불리언배열과 인덱싱할배열이 같은 크기.
print(arr[bool_arr])

[0 2 4]


In [72]:
# 값 수정

arr = np.array( [ [ 0, 1, 2 ], 
                  [ 3, 4, 5 ],
                  [ 6, 7, 8 ] ])

arr [0,0]=1
print(arr)

[[1 1 2]
 [3 4 5]
 [6 7 8]]


In [120]:
#연산
#[1,2,1]+[3,4,'숫자']

a = np.array([1,2,3])
b = np.array([4,5,6])

c = a+b
print(type(c),c)

c = 5*a
print(c)

c = 2 + 5 * b - a
print(c)

# == 사용하기

c = np.array([21,25,24])
print(c == 25)

d = c == 21
# d = np.array([True, False, False])
print(d)

<class 'numpy.ndarray'> [5 7 9]
[ 5 10 15]
[21 25 29]
[False  True False]
[ True False False]
